function stretch_sp = CreateStretchSpring (stretch_sp, undefLen, nodes_index, optional_stiffness)

global MultiRod

% default value for stiffness
if nargin > 5
  stiffness = optional_stiffness;
else
  stiffness = MultiRod.EA;
end

% n_DOF= numel(q);

stretch_sp.stiff = stiffness;
stretch_sp.refLen = undefLen;
stretch_sp.nodes_ind = nodes_index;
stretch_sp.ind = [mapNodetoDOF(nodes_index(1)); mapNodetoDOF(nodes_index(2))];

% % to store node positions with time
% stretch_sp.node1p = q(mapNodetoDOF(nodes_index(1)))';
% stretch_sp.node2p = q(mapNodetoDOF(nodes_index(2)))';


% to store forces generated by the spring
stretch_sp.dF = zeros(6, 1);
stretch_sp.dJ = zeros(6, 6);

end
