function floor_friction_g1_partial_dfr_dfn = floor_friction_g1_partial_dfr_dfn_func(in1)
%FLOOR_FRICTION_G1_PARTIAL_DFR_DFN_FUNC
%    FLOOR_FRICTION_G1_PARTIAL_DFR_DFN = FLOOR_FRICTION_G1_PARTIAL_DFR_DFN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Sep-2024 09:17:50

dt = in1(:,7);
mu = in1(:,6);
x1s_x = in1(:,1);
x1s_y = in1(:,2);
x1s_x0 = in1(:,3);
x1s_y0 = in1(:,4);
t2 = abs(dt);
t3 = 1.0./dt;
t4 = -x1s_x0;
t5 = -x1s_y0;
t6 = 1.0./t2.^2;
t7 = t4+x1s_x;
t8 = t5+x1s_y;
t9 = abs(t7);
t10 = abs(t8);
t11 = t9.^2;
t12 = t10.^2;
t13 = t6.*t11;
t14 = t6.*t12;
t15 = t13+t14;
t16 = 1.0./sqrt(t15);
floor_friction_g1_partial_dfr_dfn = [-mu.*t3.*t7.*t16;-mu.*t3.*t8.*t16];
end
