function floor_friction_partial_dfr_dfn = floor_friction_partial_dfr_dfn_func(in1)
%FLOOR_FRICTION_PARTIAL_DFR_DFN_FUNC
%    FLOOR_FRICTION_PARTIAL_DFR_DFN = FLOOR_FRICTION_PARTIAL_DFR_DFN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Sep-2024 09:17:50

K2 = in1(:,8);
dt = in1(:,7);
mu = in1(:,6);
x1s_x = in1(:,1);
x1s_y = in1(:,2);
x1s_x0 = in1(:,3);
x1s_y0 = in1(:,4);
t2 = abs(dt);
t3 = 1.0./dt;
t4 = -x1s_x0;
t5 = -x1s_y0;
t6 = 1.0./t2.^2;
t7 = t4+x1s_x;
t8 = t5+x1s_y;
t9 = abs(t7);
t10 = abs(t8);
t11 = t9.^2;
t12 = t10.^2;
t13 = t6.*t11;
t14 = t6.*t12;
t15 = t13+t14;
t16 = sqrt(t15);
t17 = 1.0./t16;
t18 = K2.*t16;
t19 = -t18;
t20 = exp(t19);
t21 = t20+1.0;
t22 = 1.0./t21;
t23 = t22.*2.0;
t24 = t23-1.0;
floor_friction_partial_dfr_dfn = [-mu.*t3.*t7.*t17.*t24;-mu.*t3.*t8.*t17.*t24];
end
